-- Insert Workout Types
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Chest');
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Legs');
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Arms');
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Back');
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Shoulders');
INSERT INTO WORKOUTTYPE (DAY_NAME) VALUES ('Cardio');

-- Insert Exercise Categories
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Leg Press');
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Chest Press');
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Dumbbell Curl');
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Lat Pulldown');
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Shoulder Press');
INSERT INTO EXERCISECATEGORY (CATEGORY_NAME) VALUES ('Treadmill');

-- Insert Exercises
-- For Leg Press
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (1, 'Hammer Strength', '45 degree leg press machine');
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (1, 'Cybex', 'Plate loaded leg press');

-- For Chest Press
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (2, 'Freeweight', 'Flat bench press');
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (2, 'Hammer Strength', 'Incline chest press machine');

-- For Dumbbell Curl
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (3, 'Freeweight', 'Standard dumbbell curl');

-- For Lat Pull Down
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (4, 'Life Fitness', 'High pulley lat pull');
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (4, 'Technogym', 'Cable lat pulldown');

-- For Shoulder Press
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (5, 'Freeweight', 'Seated dumbbell shoulder press');
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (5, 'Hammer Strength', 'Vertical grip shoulder press');

-- For Treadmill
INSERT INTO EXERCISE (EXERCISE_CATEGORY_ID, MANUFACTURER, COMMENTS) VALUES (6, 'Life Fitness', 'Treadmill running machine');

-- Insert Workouts
INSERT INTO WORKOUT (WORKOUT_TIME, WORKOUT_TITLE, WORKOUTTYPE_ID) VALUES ('2023-01-01 09:00:00', 'New Year Blast', 1);
INSERT INTO WORKOUT (WORKOUT_TIME, WORKOUT_TITLE, WORKOUTTYPE_ID) VALUES ('2023-02-01 10:00:00', 'Leg Day Madness', 2);
INSERT INTO WORKOUT (WORKOUT_TIME, WORKOUT_TITLE, WORKOUTTYPE_ID) VALUES ('2023-03-01 08:00:00', 'Back to Basics', 4);
INSERT INTO WORKOUT (WORKOUT_TIME, WORKOUT_TITLE, WORKOUTTYPE_ID) VALUES ('2023-04-01 07:30:00', 'Shoulder Strength', 5);
INSERT INTO WORKOUT (WORKOUT_TIME, WORKOUT_TITLE, WORKOUTTYPE_ID) VALUES ('2023-05-01 06:30:00', 'Morning Cardio', 6);

-- Insert Workout Exercise Selections
-- For New Year Blast (Chest)
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (1, 4, 10, 8, 7);
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (1, 3, 12, 7, 8);

-- For Leg Day Madness (Legs)
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (2, 1, 8, 9, 8);
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (2, 2, 10, 8, 7);

INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (3, 7, 12, 7, 9);
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (3, 8, 10, 6, 8);

INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (4, 9, 8, 8, 7);
INSERT INTO WORKOUTEXERCISESELECTION (WORKOUT_ID, EXERCISE_NAME_ID, REPS, DIFFICULTY_SCORE, PERCEIVED_STIMULATION_SCORE) VALUES (4, 10, 10, 7, 6);



