DROP TABLE IF EXISTS WORKOUTEXERCISESELECTION;

DROP TABLE IF EXISTS WORKOUT;

DROP TABLE IF EXISTS EXERCISE;

DROP TABLE IF EXISTS EXERCISECATEGORY;

DROP TABLE IF EXISTS WORKOUTTYPE;

-- Create Workout Type Table
CREATE TABLE WORKOUTTYPE (
	UID SERIAL PRIMARY KEY,
	DAY_NAME VARCHAR(255) NOT NULL
	-- Like "Chest", "Legs", "Arms"...
);

-- Create Exercise Type Table
-- This table is mainly useful for machine exersises. It is used so there can be 
-- a sperate excerise entry for each machine but a general exersice catagory for 
-- that machine type. For example there would be a "Leg Press" catagory but exercises 
-- for "Hammer Strenght", "Cybex".
CREATE TABLE EXERCISECATEGORY (
	UID SERIAL PRIMARY KEY,
	CATEGORY_NAME VARCHAR(255) NOT NULL
);

-- Create Exercise Table
CREATE TABLE EXERCISE (
	UID SERIAL PRIMARY KEY,
	EXERCISE_CATEGORY_ID INT NOT NULL,
	MANUFACTURER VARCHAR(255),
	-- "Freeweight" if the excersice is a free weight excerise. Only needed for machine movements like "Machine Chest Press" which could be "Hammer Strength"
	COMMENTS TEXT,
	FOREIGN KEY (EXERCISE_CATEGORY_ID) REFERENCES EXERCISECATEGORY (UID)
);

-- Create Workout Table
CREATE TABLE WORKOUT (
	UID SERIAL PRIMARY KEY,
	WORKOUT_TIME TIMESTAMP NOT NULL,
	WORKOUT_TITLE VARCHAR(255) NOT NULL,
	WORKOUTTYPE_ID INT NOT NULL,
	FOREIGN KEY (WORKOUTTYPE_ID) REFERENCES WORKOUTTYPE (UID)
);

-- Create Workout Exercise Selection Table
CREATE TABLE WORKOUTEXERCISESELECTION (
	UID SERIAL PRIMARY KEY,
	WORKOUT_ID INT NOT NULL,
	EXERCISE_NAME_ID INT NOT NULL,
	REPS INT,
	DIFFICULTY_SCORE INT,
	PERCEIVED_STIMULATION_SCORE INT,
	FOREIGN KEY (WORKOUT_ID) REFERENCES WORKOUT (UID),
	FOREIGN KEY (EXERCISE_NAME_ID) REFERENCES EXERCISE (UID)
);