DROP TABLE IF EXISTS WORKOUTEXERCISESELECTION;

DROP TABLE IF EXISTS WORKOUT;

DROP TABLE IF EXISTS EXERCISE;

DROP TABLE IF EXISTS EXERCISETYPE;

-- Create Exercise Type Table
CREATE TABLE EXERCISETYPE (
	UID SERIAL PRIMARY KEY,
	TYPE_OF_MOVEMENT VARCHAR(255) NOT NULL
);

-- Create Exercise Table
CREATE TABLE EXERCISE (
	EXERCISE_NAME VARCHAR(255) PRIMARY KEY,
	EXERCISE_TYPE_ID INT NOT NULL,
	MANUFACTURER VARCHAR(255),
	COMMENTS TEXT,
	FOREIGN KEY (EXERCISE_TYPE_ID) REFERENCES EXERCISETYPE (UID)
);

-- Create Workout Table
CREATE TABLE WORKOUT (
	UID SERIAL PRIMARY KEY,
	WORKOUT_TIME TIMESTAMP NOT NULL
);

-- Create Workout Exercise Selection Table
CREATE TABLE WORKOUTEXERCISESELECTION (
	UID SERIAL PRIMARY KEY,
	WORKOUT_ID INT NOT NULL,
	EXERCISE_NAME VARCHAR(255) NOT NULL,
	REPS INT,
	DIFFICULTY_SCORE INT,
	PERCEIVED_STIMULATION_SCORE INT,
	FOREIGN KEY (WORKOUT_ID) REFERENCES WORKOUT (UID),
	FOREIGN KEY (EXERCISE_NAME) REFERENCES EXERCISE (EXERCISE_NAME)
);